# Docker compose file to run a docker container of the latest Substrate master branch.
#
# Before you can run this script, you need to install Docker and 'Docker Compose' on your machine.
# Please follow the steps described here (including the prerequisites): https://docs.docker.com/compose/install/
#
# Usage:
# 1. BUILD: Run `docker-compose pull && docker-compose up -d` to pull the latest docker imaged and run docker-compose in detached mode. This will run the substrate container in the background.
# 2. INFO: Run `docker ps` to get a list of Docker containers running in the background including their mapped ports on localhost
# 3. TEST: Run `docker-compose logs -f js-api-tests` to run the API tests and print the logs
# 4. QUIT: Run `docker-compose down` to stop and remove all running containers.
#
# Provided Endpoints for localhost:
#   - Substrate Master: ws://127.0.0.1:9945/
#
# Find more Docker images of Substrate https://hub.docker.com/r/parity/substrate/tags
# Find more Docker images of Polkadot https://hub.docker.com/r/parity/polkadot/tags


version: "3.7"
services:
  substrate-master:
    image: parity/substrate:latest
    ports:
      - "9944:9944"
      - "9933:9933"
    networks:
      - internet
    command:
      - "--dev"
      - "--ws-external"
      - "--rpc-external"

networks:
  internet:
